name: CI-quality
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
        with:
          extraKey: quality-check
      - uses: coursier/setup-action@v1
        with:
          jvm: zulu:8
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
        with:
          sbt-version: 1.11.0
      - name: ScalaFmt
        id: fmt
        run: sbt scalafmtCheckAll
